In [1]:
print("hello")

hello


In [2]:
import numpy as np
print('NumPy version:', np.__version__)
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print('Array:', a)
print('Shape:', a.shape)   # (5,)  — 1-D, 5 elements
print('Dtype:', a.dtype)   # int64 by default
print('Ndim:', a.ndim)     # 1

# 2-D array (matrix)
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print('Shape:', mat.shape)   # (2, 3) — 2 rows, 3 cols
print(mat)

import numpy as np
# Convenience constructors
 
print(np.zeros((3,4)))        # 3*4 matrix of 0.0
print(np.ones((2,3), dtype=int))
print(np.eye(3))              # 3x3 identity
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

NumPy version: 2.4.2
Array: [1 2 3 4 5]
Shape: (5,)
Dtype: int64
Ndim: 1
Shape: (2, 3)
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [3]:
import numpy as np
# Convenience constructors
 
print(np.zeros((3,4)))        # 3*4 matrix of 0.0
print(np.ones((2,3), dtype=int))
print(np.eye(3))              # 3x3 identity
print(np.arange(0,10,2))
print(np.linspace(0,1,5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
# Random arrays - always seed
rng = np. random.default_rng(seed=42)
rand_mat = rng.integers(low=0, high=100, size=(4,5))
print(rand_mat)

[[ 8 77 65 43 43]
 [85  8 69 20  9]
 [52 97 73 76 71]
 [78 51 12 83 45]]
